# Generated by Django 4.2.23 on 2025-07-01 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.IntegerField(verbose_name=django.core.validators.MaxLengthValidator(10))),
            ],
        ),
    ]
