# Generated by Django 4.2.23 on 2025-07-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameblog',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='gameblog',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
