# Generated by Django 4.2.23 on 2025-07-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_gamepurchase_games_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepurchase',
            name='contact',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='gamepurchase',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
