# Generated by Django 4.2.23 on 2025-07-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_gameblog_slug_alter_gameblog_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameblog',
            name='slug',
        ),
    ]
